### ISSUE TITLE
Demo app please

### ISSUE THREAD

**Issue by holgersindbaek** [dam13n/motion-swipe#1]
You have one?

**Comment by dam13n** [comment]
Hey @holgersindbaek. Sorry I don't have a demo app yet. I'd love to get one up for you if I can make time... I'm open to adding one that anyone is willing to provide too.

**Comment by opes** [comment]
A demo app would be great. Expanding on the documentation in the time being would be helpful as well.

**Comment by dam13n** [comment]
Alright, I'm gonna do it! No promises, but I'll try to do make a demo app this week.

**Comment by dam13n** [comment]
@holgersindbaek @opes I added an ugly but working demo. There may be some more updates needed, so please create issues or make fixes with PRs when you find them.

**Comment by opes** [comment]
@dam13n Awesome! I will check it out and make any fixes if I find they are needed. Thank you so much!
